name: "PROBPROG 2020"
url: http://probprog-conference.github.io
#baseurl: /
permalink: /:year/:month/:day/:title
timezone: America/New_York

navigation:
- text: Program
  url: /
- text: Schedule
  url: /schedule/
- text: Registration
  url: /registration/
- text: Conduct
  url: /conduct/
