name: "PROBPROG 2018"
url: http://probprog-conference.github.io
baseurl: /2018
permalink: /:year/:month/:day/:title
timezone: America/New_York

navigation:
- text: Overview
  url: /
- text: Schedule
  url: /schedule/
- text: Registration
  url: /registration/
- text: Conduct
  url: /conduct/
